"""add calibration_runs and calibration_responses tables

Revision ID: 0c8515049be0
Revises: 61bd2246a118
Create Date: 2026-04-01 21:43:23.448413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8515049be0'
down_revision: Union[str, Sequence[str], None] = '61bd2246a118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_count', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=False),
    sa.Column('model_band', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('extracted_answer', sa.String(length=500), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['calibration_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'model_id', 'problem_id', name='uq_run_model_problem')
    )
    op.create_index('ix_calibration_model_correct', 'calibration_responses', ['model_id', 'is_correct'], unique=False)
    op.create_index(op.f('ix_calibration_responses_model_band'), 'calibration_responses', ['model_band'], unique=False)
    op.create_index(op.f('ix_calibration_responses_model_id'), 'calibration_responses', ['model_id'], unique=False)
    op.create_index(op.f('ix_calibration_responses_problem_id'), 'calibration_responses', ['problem_id'], unique=False)
    op.create_index(op.f('ix_calibration_responses_run_id'), 'calibration_responses', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibration_responses_run_id'), table_name='calibration_responses')
    op.drop_index(op.f('ix_calibration_responses_problem_id'), table_name='calibration_responses')
    op.drop_index(op.f('ix_calibration_responses_model_id'), table_name='calibration_responses')
    op.drop_index(op.f('ix_calibration_responses_model_band'), table_name='calibration_responses')
    op.drop_index('ix_calibration_model_correct', table_name='calibration_responses')
    op.drop_table('calibration_responses')
    op.drop_table('calibration_runs')
    # ### end Alembic commands ###
