"""initial schema with expanded problem model

Revision ID: 61bd2246a118
Revises: 
Create Date: 2026-04-01 15:47:23.861772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bd2246a118'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('contest_family', sa.String(length=50), nullable=False),
    sa.Column('contest_year', sa.Integer(), nullable=True),
    sa.Column('contest_round', sa.String(length=30), nullable=True),
    sa.Column('contest_level', sa.String(length=30), nullable=True),
    sa.Column('problem_number', sa.Integer(), nullable=True),
    sa.Column('problem_text', sa.Text(), nullable=False),
    sa.Column('text_format', sa.String(length=10), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.Column('answer_type', sa.String(length=30), nullable=True),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('official_solution', sa.Text(), nullable=True),
    sa.Column('mark_explanation', sa.Text(), nullable=True),
    sa.Column('mark_audio_url', sa.String(length=500), nullable=True),
    sa.Column('mark_diagram_url', sa.String(length=500), nullable=True),
    sa.Column('personality_variants', sa.JSON(), nullable=True),
    sa.Column('explanation_rating', sa.Float(), nullable=True),
    sa.Column('explanation_flags', sa.Integer(), nullable=False),
    sa.Column('latex_content', sa.Text(), nullable=True),
    sa.Column('difficulty_band', sa.Integer(), nullable=True),
    sa.Column('difficulty_source', sa.String(length=30), nullable=True),
    sa.Column('primary_domain', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('grade_band', sa.String(length=20), nullable=True),
    sa.Column('problem_style', sa.String(length=50), nullable=True),
    sa.Column('requires_visual', sa.Boolean(), nullable=False),
    sa.Column('source_dataset', sa.String(length=50), nullable=True),
    sa.Column('source_path', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_answer_type'), 'problems', ['answer_type'], unique=False)
    op.create_index(op.f('ix_problems_contest_family'), 'problems', ['contest_family'], unique=False)
    op.create_index(op.f('ix_problems_contest_year'), 'problems', ['contest_year'], unique=False)
    op.create_index('ix_problems_difficulty_domain', 'problems', ['primary_domain', 'difficulty_band'], unique=False)
    op.create_index(op.f('ix_problems_external_id'), 'problems', ['external_id'], unique=True)
    op.create_index(op.f('ix_problems_grade_band'), 'problems', ['grade_band'], unique=False)
    op.create_index('ix_problems_grade_subject', 'problems', ['grade_band', 'subject'], unique=False)
    op.create_index(op.f('ix_problems_primary_domain'), 'problems', ['primary_domain'], unique=False)
    op.create_index(op.f('ix_problems_source_dataset'), 'problems', ['source_dataset'], unique=False)
    op.create_index('ix_problems_source_lookup', 'problems', ['contest_family', 'contest_year', 'contest_round', 'problem_number'], unique=False)
    op.create_index(op.f('ix_problems_subject'), 'problems', ['subject'], unique=False)
    op.create_table('skill_nodes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('source_mapping', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_nodes_domain'), 'skill_nodes', ['domain'], unique=False)
    op.create_index(op.f('ix_skill_nodes_level'), 'skill_nodes', ['level'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('roast_preference', sa.Float(), nullable=False),
    sa.Column('mini_game_preference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_ratings',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_rating', sa.Float(), nullable=False),
    sa.Column('difficulty_rd', sa.Float(), nullable=False),
    sa.Column('difficulty_volatility', sa.Float(), nullable=False),
    sa.Column('solve_rate', sa.Float(), nullable=True),
    sa.Column('discrimination', sa.Float(), nullable=False),
    sa.Column('guessing', sa.Float(), nullable=False),
    sa.Column('calibration_source', sa.String(length=30), nullable=True),
    sa.Column('mini_model_solve_rate', sa.Float(), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('last_calibrated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_node_id', sa.String(length=80), nullable=False),
    sa.Column('lesson_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('worked_examples', sa.JSON(), nullable=True),
    sa.Column('visual_aids', sa.JSON(), nullable=True),
    sa.Column('mark_recording_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_skill_node_id'), 'lessons', ['skill_node_id'], unique=True)
    op.create_table('practice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('problems_attempted', sa.Integer(), nullable=False),
    sa.Column('problems_correct', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Float(), nullable=True),
    sa.Column('rating_after', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_student_id'), 'practice_sessions', ['student_id'], unique=False)
    op.create_table('problem_figures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('figure_path', sa.String(length=500), nullable=False),
    sa.Column('figure_type', sa.String(length=30), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_figures_problem_id'), 'problem_figures', ['problem_id'], unique=False)
    op.create_table('problem_skill_tags',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tagged_by', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], ),
    sa.PrimaryKeyConstraint('problem_id', 'skill_node_id')
    )
    op.create_table('student_domain_ratings',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_deviation', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'domain')
    )
    op.create_table('student_global_ratings',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_deviation', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('nodes_proficient', sa.Integer(), nullable=False),
    sa.Column('nodes_mastered', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('student_ratings',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('skill_node_id', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_deviation', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('mastery_state', sa.String(length=20), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'skill_node_id')
    )
    op.create_index(op.f('ix_student_ratings_domain'), 'student_ratings', ['domain'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('student_answer', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('rating_before', sa.Float(), nullable=False),
    sa.Column('rating_after', sa.Float(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_problem_id'), 'answers', ['problem_id'], unique=False)
    op.create_index(op.f('ix_answers_session_id'), 'answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_session_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_problem_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_student_ratings_domain'), table_name='student_ratings')
    op.drop_table('student_ratings')
    op.drop_table('student_global_ratings')
    op.drop_table('student_domain_ratings')
    op.drop_table('problem_skill_tags')
    op.drop_index(op.f('ix_problem_figures_problem_id'), table_name='problem_figures')
    op.drop_table('problem_figures')
    op.drop_index(op.f('ix_practice_sessions_student_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_lessons_skill_node_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('item_ratings')
    op.drop_table('students')
    op.drop_index(op.f('ix_skill_nodes_level'), table_name='skill_nodes')
    op.drop_index(op.f('ix_skill_nodes_domain'), table_name='skill_nodes')
    op.drop_table('skill_nodes')
    op.drop_index(op.f('ix_problems_subject'), table_name='problems')
    op.drop_index('ix_problems_source_lookup', table_name='problems')
    op.drop_index(op.f('ix_problems_source_dataset'), table_name='problems')
    op.drop_index(op.f('ix_problems_primary_domain'), table_name='problems')
    op.drop_index('ix_problems_grade_subject', table_name='problems')
    op.drop_index(op.f('ix_problems_grade_band'), table_name='problems')
    op.drop_index(op.f('ix_problems_external_id'), table_name='problems')
    op.drop_index('ix_problems_difficulty_domain', table_name='problems')
    op.drop_index(op.f('ix_problems_contest_year'), table_name='problems')
    op.drop_index(op.f('ix_problems_contest_family'), table_name='problems')
    op.drop_index(op.f('ix_problems_answer_type'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
